

#nullable enable
namespace fastpix.io.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Displays the result of the request.
    /// </summary>
    [Serializable]
    public class CreateSigningKeyResponseDTO
    {

        /// <summary>
        /// A unique identifier is generated by FastPix for the signing keys.
        /// </summary>
        [SerializeField]
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// A private key is a byte encoded secret key used to create a signed JSON Web Token (JWT) for authentication.
        /// </summary>
        [SerializeField]
        [JsonProperty("privateKey")]
        public string? PrivateKey { get; set; }

        /// <summary>
        /// Time the media was generated, defined as a localDateTime (UTC Time).
        /// </summary>
        [SerializeField]
        [JsonProperty("createdAt")]
        public DateTime? CreatedAt { get; set; }
    }
}