

#nullable enable
namespace fastpix.io.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    using fastpix.io.Models.Components;
    
    [Serializable]
    public class GetAllSigningKeyResponseDTO
    {

        /// <summary>
        /// A unique identifier is generated by FastPix for the signing keys.
        /// </summary>
        [SerializeField]
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Time the media was generated, defined as a localDateTime (UTC Time).
        /// </summary>
        [SerializeField]
        [JsonProperty("createdAt")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// It display a specific setup where all operations are conducted.
        /// </summary>
        [SerializeField]
        [JsonProperty("workspace")]
        public List<SigningKeyWorkspaceDTO>? Workspace { get; set; }

        /// <summary>
        /// Pagination organizes content into pages for better readability and navigation.
        /// </summary>
        [SerializeField]
        [JsonProperty("pagination")]
        public SingingKeysPagination? Pagination { get; set; }
    }
}