

#nullable enable
namespace fastpix.io.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    using fastpix.io.Models.Components;
    
    /// <summary>
    /// A collection of Playback ID objects utilized for crafting HLS playback urls.
    /// </summary>
    [Serializable]
    public class PlaybackId
    {

        /// <summary>
        /// A unique identifier is generated by FastPix for the playbacks.
        /// </summary>
        [SerializeField]
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Access policy for media content
        /// </summary>
        [SerializeField]
        [JsonProperty("accessPolicy")]
        public AccessPolicy? AccessPolicy { get; set; }

        /// <summary>
        /// Controls access based on domains and user agents. Defines a default policy (either &quot;allow&quot; or &quot;deny&quot;) and provides lists for explicitly allowed or denied domains and user agents.
        /// </summary>
        [SerializeField]
        [JsonProperty("accessRestrictions")]
        public PlaybackIdAccessRestrictions? AccessRestrictions { get; set; }
    }
}