name: Build and Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: nuget

    steps:
      - uses: actions/checkout@v4

      - name: Install OS dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore src/FastPix/FastPix.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/FastPix/FastPix.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./nupkg src/FastPix/FastPix.csproj

      - name: Publish to NuGet
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY_UNITY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY_UNITY }}